extends: default

rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 132
    level: warning

  # accept both     key:
  #                   - item
  #
  # and             key:
  #                 - item
  indentation:
    indent-sequences: whatever
