# Basic MOV.AI Flow™ cluster configuration with Redis and Redis local databases.
#
# WARNING:
#   This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# MOVAI_REGISTRY               - Docker images registry
#                                Default: pubregistry.aws.cloud.mov.ai
# MOVAI_UID                    - User ID in MOVAI containers
#                                Default: 1000
# MOVAI_DEVICE_NAME            - Docker containers identifier
#                                Default: Flow
# MOVAI_ENV                    - Docker containers environment (develop/qa/release)
#                                Default: qa
#
# Those configurations are useful mostly in case of standalone testing/running MOV.AI Flow™ in test/try-out mode
#
# STUDIO_USER_USERNAME   - Username for the administrator account (if requested).
#                          Default: movai
# STUDIO_USER_PASSWORD   - Password for the administrator account (if requested).
#                          Default: movai
#
# STUDIO_SIMU_GUI        - Default Simulation GUI: WorldLauncher
#
# STUDIO_SIMU_PLUGIN_PACKAGES - List of movai ignition plugin packages to be installed.
#                               Default: movai-ign-plugin-world-launcher
#
# STUDIO_DB_PACKAGES     - List of packages initializing the DB.
#                          Default: movai-baseline
#
# STUDIO_APP_PACKAGES    - List of packages initializing the web apps.
#                          Default: movai-launcher movai-ide
#
# STUDIO_SPAWNER_PACKAGES - List of packages initializing the spawner.
#                          Default: ros-noetic-movai-ce-demos
#
# SPAWNER_PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting ROS spawner.
#                                Default: ''
#

# Feel free to modify this file to suit your needs.
---
version: "3.9"
x-movai-common:
  &movai-common
  environment:
    &movai-common-env
    MOVAI_ENV: ${MOVAI_ENV:-qa}
    MOVAI_STDOUT_VERBOSITY_LEVEL: 10  # DEBUG
    MOVAI_LOGFILE_VERBOSITY_LEVEL: 30  # WARNING
    MOVAI_GENERAL_VERBOSITY_LEVEL: 10  # DEBUG
    MOVAI_HEALTHNODE_VERBOSITY_LEVEL: 0
    MOVAI_USERSPACE: /opt/mov.ai/user
    MOVAI_MANAGER_URI: http://localhost:5004
    DEVICE_NAME: ${MOVAI_DEVICE_NAME:-flow}
    FLEET_NAME: ${FLEET_NAME:?missing FLEET_NAME ENV var}
    FLEET_TOKEN: ${FLEET_TOKEN:?missing FLEET_TOKEN ENV var}
    REDIS_LOCAL_PORT: 6380
    REDIS_LOCAL_HOST: localhost
    REDIS_MASTER_PORT: 6379
    REDIS_MASTER_HOST: localhost
    ROS_MASTER_URI: http://localhost:22322/
    PUBLIC_IP: ${PUBLIC_IP:-127.0.0.1}
    LOG_HTTP_HOST: http://localhost:5004
    IGNITION_MOVAI: "true"
    IGN_PARTITION: ${IGN_PARTITION:?missing IGN_PARTITION ENV var}
    IGNITION_VERSION: fortress
    APT_AUTOINSTALL: "once"
    APT_KEYS_URL_LIST: "https://artifacts.aws.cloud.mov.ai/repository/movai-applications/gpg"
    APT_REPOS_LIST: "deb [arch=all] https://artifacts.aws.cloud.mov.ai/repository/ppa-public main main"
  volumes:
    - ./userspace:/opt/mov.ai/user
    - ./shared:/opt/mov.ai/shared
    - ./logs:/opt/mov.ai/logs
  # user: "${MOVAI_UID:-1000}:0"
  depends_on:
    &movai-common-depend
    redis-local:
      condition: service_healthy
    redis-master:
      condition: service_healthy
  extra_hosts:
    &movai-common-extra-hosts
    backend: 127.0.0.1
    spawner: 127.0.0.1
    redis-master: 127.0.0.1
    redis-local: 127.0.0.1
    redis-slave: 127.0.0.1
    ros-master: 127.0.0.1

services:
  redis-master:
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/redis2:v1.0.10
    container_name: redis-master-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    network_mode: host
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/6379"]
      start_period: 3s
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - redis-master-flow-volume:/data
      - ./redis/master.conf:/etc/redis.conf
    environment:
      <<: *movai-common-env
      APT_INSTALL_LIST: $STUDIO_DB_PACKAGES
      REDIS_PORT: $REDIS_MASTER_PORT
    restart: unless-stopped
    extra_hosts:
      <<: *movai-common-extra-hosts

  redis-local:
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/redis2:v1.0.10
    container_name: redis-local-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    network_mode: host
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/6380"]
      start_period: 3s
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - redis-local-flow-volume:/data
      - ./redis/local.conf:/etc/redis.conf
    restart: unless-stopped
    environment:
      - REDIS_PORT=$REDIS_LOCAL_PORT
    extra_hosts:
      <<: *movai-common-extra-hosts

  backend:
    <<: *movai-common
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/backend-noetic:1.0.0.23
    container_name: backend-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    network_mode: host
    depends_on:
      <<: *movai-common-depend
    environment:
      <<: *movai-common-env
      APT_INSTALL_LIST: "$STUDIO_APP_PACKAGES"
      HTTP_PORT: ${STUDIO_WEB_PORT}
      DEFAULT_USERNAME: movai
      DEFAULT_PASSWORD: movai
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:?missing JWT_SECRET_KEY ENV var}
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/${STUDIO_WEB_PORT}"]
      start_period: 5s
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    extra_hosts:
      <<: *movai-common-extra-hosts

  ros-master:
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/ros-master-noetic:v1.0.2
    privileged: true
    network_mode: host
    depends_on:
      backend:
        condition: service_healthy
    container_name: ros-master-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    healthcheck:
      test: ["CMD-SHELL", ". /opt/ros/noetic/setup.sh && /opt/ros/noetic/bin/rostopic list | grep -w '/rosout' >> /dev/null"]
      start_period: 3s
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    extra_hosts:
        <<: *movai-common-extra-hosts

  spawner:
    <<: *movai-common
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/spawner-ign-noetic:v3.0.9
    privileged: true
    network_mode: host
    depends_on:
      <<: *movai-common-depend
      backend:
        condition: service_healthy
    healthcheck:
      test: pgrep -f "/usr/bin/python3 -m flow_initiator"
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 1
    container_name: spawner-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /run/movai:/var/run/movai
      - ./userspace:/opt/mov.ai/user
      - ./shared:/opt/mov.ai/shared
      - ./logs:/opt/mov.ai/logs
    environment:
      <<: *movai-common-env
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      APP_NAME: spawner
      APT_INSTALL_LIST: $STUDIO_SPAWNER_PACKAGES
    restart: unless-stopped
    extra_hosts:
      <<: *movai-common-extra-hosts

  simulator:
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/ignition-gazebo:v1.0.5
    container_name: simulator-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    profiles: ["simulator"]
    environment:
      <<: *movai-common-env
      DISPLAY: "$DISPLAY"
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: "$XAUTH"
      IGN_GAZEBO_SYSTEM_PLUGIN_PATH: /movai_ign_plugins/system:/models_database/plugins/system
      IGN_GUI_PLUGIN_PATH: /movai_ign_plugins/gui:/models_database/plugins/gui
      IGN_GAZEBO_RESOURCE_PATH: /models_database/my_models
      APT_INSTALL_LIST: $STUDIO_SIMU_PLUGIN_PACKAGES
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $XAUTH:$XAUTH
      - ./models_database:/models_database
      - ./models_database/fuel:/root/.ignition/fuel
    network_mode: host
    privileged: true
    tty: true
    healthcheck:
      test: pgrep -f "ign gui -s $STUDIO_SIMU_GUI"
      start_period: 3s
      interval: 30s
      timeout: 3s
      retries: 10
    command: ign gui -s $STUDIO_SIMU_GUI
    extra_hosts:
      <<: *movai-common-extra-hosts

  ros-tools:
    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/ros-tools-ce:v1.0.4
    container_name: ros-tools-$MOVAI_DEVICE_NAME
    logging:
      driver: "journald"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
    profiles: ["tools"]
    environment:
      <<: *movai-common-env
      DISPLAY: "$DISPLAY"
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: "$XAUTH"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $XAUTH:$XAUTH
      - ./rviz/:/headless/.rviz/:rw
    network_mode: host
    privileged: true
    tty: true
    entrypoint: /bin/bash
    command:
      - -ic
      - |
        exec /usr/bin/rviz
    extra_hosts:
      <<: *movai-common-extra-hosts

volumes:
  redis-master-flow-volume:
  redis-local-flow-volume:
