#!/bin/bash
# pre remove actions
# clean unziped files

SERVICE_NAME=movai-flow
APP_PATH=/usr/share/$SERVICE_NAME
DOCKER_COMPOSE_CONF=$APP_PATH/docker-compose.yml
DOCKER_COMPOSE_ENV=$APP_PATH/.env
DOCKER_COMPOSE_BIN=$(which docker-compose || echo /usr/local/bin/docker-compose)

# Remove the package (but not its configuration files)
if [ "$1" = "remove" ]; then
    pushd $APP_PATH || echo ""
    $DOCKER_COMPOSE_BIN -f $DOCKER_COMPOSE_CONF down || true
    popd || echo ""

    rm -r $APP_PATH
fi