#!/bin/bash
SCRIPTNAME=SIMULATOR
SERVICE_NAME=movai-flow
APP_PATH=${APP_PATH:-/usr/share/$SERVICE_NAME}
CONFIG_PATH=${CONFIG_PATH:-/$APP_PATH/config}
DOCKER_COMPOSE_CONF=$APP_PATH/docker-compose.yml
DOCKER_COMPOSE_CONF_MHOST=$APP_PATH/docker-compose-host.yml
DOCKER_COMPOSE_NVIDIA_CONF=$APP_PATH/docker-compose-nvidia.yml
DOCKER_COMPOSE_NVIDIA_CONF_MHOST=$APP_PATH/docker-compose-nvidia-host.yml
DOCKER_COMPOSE_BIN=$(which docker-compose || echo /usr/local/bin/docker-compose)

Output() {
  # Prepare base message
  Message="MOV.AI Flow™ $SCRIPTNAME: $1"

  # Output the message even if a blank message (make output nice)
  echo "$Message"

  # Return if blank.
  if [ "$1" = "" ]; then
    return
  fi

  # Output to log
  if which journalctl > /dev/null 2>&1
  then
    echo MESSAGE="$Message" | head -n 1 | logger --journald
  else
    echo "$Message" | logger
  fi
}

# Symlink userspace and models_database to ~/Documents/MovaiFlow
user_documents_path=$(xdg-user-dir DOCUMENTS)
Output "Creating user and models folder"
if [ ! -e "${user_documents_path}/MovaiFlow" ]; then
  mkdir -p "${user_documents_path}/MovaiFlow"
  ln -sf "$APP_PATH/userspace" "${user_documents_path}/MovaiFlow"
  ln -sf "$APP_PATH/models_database" "${user_documents_path}/MovaiFlow"
  Output "User and models folder ${user_documents_path}/MovaiFlow"
fi

Output "This terminal window will verify all MOV.AI Flow™ services are running and then launch the Ignition Simulator GUI application

(U) [^_^] (U)
"

if [ -f "$CONFIG_PATH/config.env" ]; then
  Output "Sourcing configuration"
  . "$CONFIG_PATH/config.env"
else
  Output "No configuration found"
fi

if [ "$NETWORK_MODE" = "host" ]; then
  compose_conf="$DOCKER_COMPOSE_CONF_MHOST"
  compose_conf_nvidia="$DOCKER_COMPOSE_NVIDIA_CONF_MHOST"
else
  compose_conf="$DOCKER_COMPOSE_CONF"
  compose_conf_nvidia="$DOCKER_COMPOSE_NVIDIA_CONF"
fi

# Check NVIDIA
Architecture="$(uname -m)"
if [ "$Architecture" = "x86_64" ]; then
  # Is there a Nvidia card present (possible HW enhanced graphical rendering)
  [ "$(echo /sys/module/nvidia/drivers/pci:nvidia/*:*:*.*)" != "/sys/module/nvidia/drivers/pci:nvidia/*:*:*.*" ] && HaveNvidia=1
  # Is there NVIDIA Container Toolkit to build and run GPU accelerated Docker containers
  [ "$(dpkg -l | grep ^ii | grep -iw nvidia-container-toolkit)" != "" ] && HaveDockerNvidia=1
fi
if [ $HaveNvidia -gt 0 ]; then
    Output "  NVIDIA GPU card found"
else
    Output "  NVIDIA GPU card not found"
fi
if [ $HaveDockerNvidia -gt 0 ]; then
    Output "  NVIDIA Container Toolkit found"
else
    Output "  NVIDIA Container Toolkit not found"
    if [ $HaveNvidia -gt 0 ]; then
      echo -e "\033[1;33mWARNING: NVIDIA GPU found but no NVIDIA Container Toolkit\e[0m"
      echo "Follow instructions on getting started with the NVIDIA Container Toolkit"
      echo -e "\thttps://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker"
    fi
fi

xhost +local:docker
if [ $HaveNvidia -gt 0 ]; then
  Output "Launching simulator for Nvidia GPU"
  exec $DOCKER_COMPOSE_BIN -f "$compose_conf_nvidia" up simulator
else
  Output "Launching simulator for integrated GPU"
  exec $DOCKER_COMPOSE_BIN -f "$compose_conf" up simulator
fi
