#!/bin/bash
SCRIPTNAME=Stopper
SERVICE_NAME=movai-flow
APP_PATH=${APP_PATH:-/usr/share/$SERVICE_NAME}
CONFIG_PATH=${CONFIG_PATH:-/etc/$SERVICE_NAME}
DOCKER_COMPOSE_CONF=$APP_PATH/docker-compose.yml
DOCKER_COMPOSE_BIN=$(which docker-compose || echo /usr/local/bin/docker-compose)
APP_URL="http://localhost:8080/api/v1/apps/mov-fe-app-ide-ce/"

Output() {
  # Prepare base message
  Message="MOV.AI Flow™ $SCRIPTNAME: $1"

  # Output the message even if a blank message (make output nice)
  echo "$Message"

  # Return if blank.
  if [ "$1" = "" ]; then
    return
  fi

  # Output to log
  if which journalctl > /dev/null 2>&1
  then
    echo MESSAGE="$Message" | logger --journald
  else
    echo "$Message" | logger
  fi
}

StopServices() {
  Output "Stopping services..."
  Output "(U) [^_^] (U)"
  Output "Terminal will close on completion, wait or press CTRL+C on failure"
  $DOCKER_COMPOSE_BIN -f $DOCKER_COMPOSE_CONF stop
}

StopServices