#!/bin/bash

/usr/local/bin/docker-compose -f /usr/share/movai-studio/launch/docker-compose.yml up -d movai-cli

/usr/local/bin/docker-compose -f /usr/share/movai-studio/launch/docker-compose.yml exec movai-cli movai-shell
