#!/bin/bash
SCRIPTNAME=Reset
SERVICE_NAME=movai-flow
APP_PATH=${APP_PATH:-/usr/share/$SERVICE_NAME}
CONFIG_PATH=${CONFIG_PATH:-/$APP_PATH/config}

DOCKER_COMPOSE_CONF=$APP_PATH/docker-compose.yml
DOCKER_COMPOSE_CONF_MHOST=$APP_PATH/docker-compose-host.yml

DOCKER_COMPOSE_BIN=$(which docker-compose || echo /usr/local/bin/docker-compose)

Output() {
  # Prepare base message
  Message="MOV.AI Flow™ $SCRIPTNAME: $1"

  # Output the message even if a blank message (make output nice)
  echo "$Message"

  # Return if blank.
  if [ "$1" = "" ]; then
    return
  fi

  # Output to log
  if which journalctl > /dev/null 2>&1
  then
    echo MESSAGE="$Message" | head -n 1 | logger --journald
  else
    echo "$Message" | logger
  fi
}

StopServices() {
  Output "Stopping containers and removing containers, networks, volumes, and images...

  (U) [^_^] (U)

  Terminal will close on completion, wait or press CTRL+C on failure"

  if [ "$NETWORK_MODE" = "host" ]; then
    compose_conf="$DOCKER_COMPOSE_CONF_MHOST"
  else
    compose_conf="$DOCKER_COMPOSE_CONF"
  fi

  sed -i -e "/^NETWORK_MODE=/s/=.*/=/" "$CONFIG_PATH/config.env"

  $DOCKER_COMPOSE_BIN -f "$compose_conf" down -v --remove-orphans -t 300
}

if [ -f "$CONFIG_PATH/config.env" ]; then
  Output "Sourcing configuration"
  . "$CONFIG_PATH/config.env"
else
  Output "No configuration found"
fi

StopServices