name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - dev
      - main
      - 'releases/**'
    paths-ignore:
      - 'CHANGELOG.md' 
jobs:
  Test-Project:
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/devops/ros-buildtools-melodic:main
      options: --user root
      credentials:
        username: ${{secrets.PORTUS_APP_USER}} 
        password: ${{secrets.PORTUS_APP_TOKEN}}

    steps:
    - name: Checkout    
      uses: actions/checkout@v2

    - name: Find Package details
      id: vars
      run: |
        PACKAGE_VERSION=$(dpkg-parsechangelog --show-field Version)
        PACKAGE_NAME=$(pkg-parsechangelog --show-field Source)
        
        echo ::set-output name=npm_pkg_name::$PACKAGE_NAME
        echo ::set-output name=npm_pkg_version::$PACKAGE_VERSION
    
    - name: Raise Version
      id: vars-after-raise
      run: | 
        PACKAGE_VERSION=${{ steps.vars.outputs.npm_pkg_version }}
        main_version=${PACKAGE_VERSION%-*}
        build_id="${PACKAGE_VERSION#*-}"
        ((raised_buildid=$build_id + 1))
        RAISED_PACKAGE_VERSION=$main_version-$raised_buildid
        echo ::set-output name=npm_pkg_version::$RAISED_PACKAGE_VERSION
      
    - name: Pack debian
      run: |
        dch -v ${{ steps.vars-after-raise.outputs.npm_pkg_version }} -D "UNRELEASED" "bump version"
        dpkg-buildpackage